index:
    path: //
    controller: App\Controller\Controller::index

noticias:
    path: /noticias/{currentPage}
    controller: App\Controller\Controller::noticias
    defaults:
      currentPage: 1

socios:
    path: /login
    controller: App\Controller\SecurityController::login

registroSocio:
    path: /registro
    controller: App\Controller\RegistrationController::register

admin:
    path: /admin
    controller: App\Controller\Controller::admin

logout:
    path: /logout
    methods: GET

inicioAdmin:
    path: /administrador/inicio
    controller: App\Controller\Controller::inicioAdmin

noticiasAdmin:
    path: /administrador/noticias
    controller: App\Controller\Controller::noticiasAdmin
    
verNoticia:
    path: /noticia/{id}
    controller: App\Controller\Controller::verNoticia

nuevaNoticia:
  path: /administrador/noticia/nueva
  controller: App\Controller\Controller::nuevaNoticia

borrarNoticia:
  path: /administrador/noticia/borrar/{id}
  controller: App\Controller\Controller::borrarNoticia

editarNoticia:
  path: /noticia/editar/{id}
  controller: App\Controller\Controller::editarNoticia

inicioAreaPrivada:
  path: /area_privada
  controller: App\Controller\Controller::inicioAreaPrivada 

#Contacto

notificacionesAdmin:
    path: /administrador/notificaciones
    controller: App\Controller\NotificacionesController::listaNotificaciones

notificacionLeida:
    path: /administrador/notificacionLeida/{id}
    controller: App\Controller\NotificacionesController::notificacionLeida

notificacionNoLeida:
    path: /administrador/notificacionNoLeida/{id}
    controller: App\Controller\NotificacionesController::notificacionNoLeida

verNotificacion:
    path: /administrador/notificacion/{id}
    controller: App\Controller\NotificacionesController::verNotificacion

nuevaNotificacion:
    path: /contacto
    controller: App\Controller\NotificacionesController::nuevaNotificacion

contactoSocios:
    path: /socio/contactoSocios
    controller: App\Controller\NotificacionesController::nuevaNotificacionSocio  
# Documentos

nuevoDocumento:
    path: /administrador/nuevoDocumento
    controller: App\Controller\DocumentosController::nuevoDocumento

documentos:
    path: /documentos
    controller: App\Controller\DocumentosController::listaDocumentos

documentosAdmin:
  path: /administrador/documentosAdmin
  controller: App\Controller\DocumentosController::documentosAdmin   

documentosSocios:
  path: /socio/documentosSocios
  controller: App\Controller\DocumentosController::documentosSocios   

borrarDocumento:
  path: /administrador/documento/borrar/{id}
  controller: App\Controller\DocumentosController::borrarDocumento

# Partidos

nuevoPartido:
    path: /administrador/nuevoPartido
    controller: App\Controller\PartidosController::nuevoPartido

nuevoEquipo:
    path: /administrador/nuevoEquipo
    controller: App\Controller\PartidosController::nuevoEquipo

partidosAdmin:
    path: /administrador/partidos
    controller: App\Controller\PartidosController::partidos

partidos:
    path: /partidos
    controller: App\Controller\PartidosController::partidos

borrarPartido:
    path: /administrador/partido/{id}
    controller: App\Controller\PartidosController::borrarPartido

listaEquipos:
    path: /administrador/listaEquipos
    controller: App\Controller\PartidosController::listaEquipos

borrarEquipo:
    path: /administrador/borrarEquipo/{id}
    controller: App\Controller\PartidosController::borrarEquipo

# Cuotas

verCuota:
    path: /socio/cuotas/{idSocio}
    controller: App\Controller\CuotasController::verCuota

nuevaCuota:
    path: /administrador/nuevaCuota/{idSocio}
    controller: App\Controller\CuotasController::nuevaCuota

editarCuota:
    path: /administrador/editarCuota/{id}
    controller: App\Controller\CuotasController::editarCuota

nuevoAño:
    path: /administrador/nuevoAño
    controller: App\Controller\CuotasController::nuevoAño

anoCompletoCuota:
    path: /administrador/editarCuota/anoCompleto/{id}
    controller: App\Controller\CuotasController::anoCompletoCuota

seisMesesCuota:
    path: /administrador/editarCuota/seisMesesCuotas/{id}
    controller: App\Controller\CuotasController::seisMesesCuota

# Socios

sociosAdmin:
    path: /administrador/socios
    controller: App\Controller\SociosController::socios

nuevoSocio:
    path: /administrador/nuevoSocio
    controller: App\Controller\SociosController::nuevoSocio

editarSocioAdmin:
    path: /administrador/editarSocio/{id}
    controller: App\Controller\SociosController::editarSocioAdmin

editarSocio:
    path: /socio/editarSocio{id}
    controller: App\Controller\SociosController::editarSocio

menuAreaPrivada:
    path: /administrador/menuAreaPrivada/{seccionActual}
    controller: App\Controller\Controller::menuAreaPrivada

borrarSocio:
  path: /administrador/borrarSocio/{id}
  controller: App\Controller\SociosController::borrarSocio
