index:
    path: /
    controller: App\Controller\Controller::index

noticias:
    path: /noticias
    controller: App\Controller\Controller::noticias

socios:
    path: /login
    controller: App\Controller\SecurityController::login

registroSocio:
    path: /registro
    controller: App\Controller\RegistrationController::register

faq:
    path: /faq
    controller: App\Controller\Controller::faq



nuevaNotificacion:
    path: /contacto
    controller: App\Controller\NotificacionesController::nuevaNotificacion

admin:
    path: /admin
    controller: App\Controller\Controller::admin

logout:
    path: /logout
    methods: GET

inicioAdmin:
    path: /administrador/inicio
    controller: App\Controller\Controller::inicioAdmin

sociosAdmin:
    path: /administrador/socios
    controller: App\Controller\Controller::sociosAdmin

noticiasAdmin:
    path: /administrador/noticias
    controller: App\Controller\Controller::noticiasAdmin

notificacionesAdmin:
    path: /administrador/notificaciones
    controller: App\Controller\NotificacionesController::listaNotificaciones

notificacionLeida:
    path: /administrador/notificacionLeida/{id}
    controller: App\Controller\NotificacionesController::notificacionLeida

notificacionNoLeida:
    path: /administrador/notificacionNoLeida/{id}
    controller: App\Controller\NotificacionesController::notificacionNoLeida

verNotificacion:
    path: /administrador/notificacion/{id}
    controller: App\Controller\NotificacionesController::verNotificacion
    
verNoticia:
    path: /noticia/{id}
    controller: App\Controller\Controller::verNoticia

nuevaNoticia:
  path: /administrador/noticia/nueva
  controller: App\Controller\Controller::nuevaNoticia

borrarNoticia:
  path: /administrador/noticia/borrar/{id}
  controller: App\Controller\Controller::borrarNoticia

editarNoticia:
  path: /noticia/editar/{id}
  controller: App\Controller\Controller::editarNoticia

inicioAreaPrivada:
  path: /area_privada
  controller: App\Controller\Controller::inicioAreaPrivada 

# Documentos

nuevoDocumento:
    path: /nuevoDocumento
    controller: App\Controller\DocumentosController::nuevoDocumento

documentos:
    path: /documentos
    controller: App\Controller\DocumentosController::listaDocumentos

documentosAdmin:
  path: /administrador/documentosAdmin
  controller: App\Controller\DocumentosController::documentosAdmin   

documentosSocios:
  path: /socio/documentosSocios
  controller: App\Controller\DocumentosController::documentosSocios   

borrarDocumento:
  path: /administrador/documento/borrar/{id}
  controller: App\Controller\DocumentosController::borrarDocumento